project_id = "psaqqtfitxevwkgzupnp"

[functions.get-mapbox-token]
verify_jwt = true

[functions.send-notification]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.check-leave-quota]
verify_jwt = true

[functions.cleanup-old-photos]
verify_jwt = false

[functions.attendance-insight]
verify_jwt = false

[functions.fetch-indonesia-holidays]
verify_jwt = false

[functions.scheduled-backup]
verify_jwt = false

[functions.checkout-reminder]
verify_jwt = false

[functions.fetch-medical-reimbursements]
verify_jwt = false